name: Inter-branch merge workflow
on:
  push:
    branches:
      - release/**

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  Merge:
    uses: dotnet/arcade/.github/workflows/inter-branch-merge-base.yml@7f6fe7faf085cb19abcb7fdbfc11d91818ce2ccf
